version: 2

builds:
  - binary: shoplazza
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/Shoplazza/shoplazza-cli/internal/build.Version={{ .Version }}
      - -X github.com/Shoplazza/shoplazza-cli/internal/build.Date={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "shoplazza-cli-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  mode: replace
  github:
    owner: Shoplazza
    name: shoplazza-cli

brews:
  - repository:
      owner: Shoplazza
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/Shoplazza/shoplazza-cli"
    description: "The official CLI for Shoplazza Open Platform"
    license: "MIT"
    install: |
      bin.install "shoplazza"
    test: |
      assert_match version.to_s, shell_output("#{bin}/shoplazza --version")
